# Generated by Django 5.2.7 on 2025-10-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_code'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection 1')
        """,
        """
            DELETE FROM store_collection
            WHERE title = 'collection 1'
        """)
    ]
